version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/vite-react-app

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root

  AfterInstall:
    - location: scripts/configure_nginx.sh
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
